
-- USER is a reserved keyword with Postgres
-- You must use double quotes in every query that user is in:
-- ex. SELECT * FROM "user";
-- Otherwise you will have errors!





CREATE TABLE "user" (
    "id" SERIAL PRIMARY KEY, 
    "username" VARCHAR (80) UNIQUE,
    "password" VARCHAR (100),
    "isAdmin" BOOLEAN DEFAULT false,
	"click_gather_sunlight" FLOAT DEFAULT 1,
  "resource_sap" FLOAT DEFAULT 0,
  "resource_treefolk" FLOAT DEFAULT 0,
  "resource_science" FLOAT DEFAULT 0,
  "resource_sunlight_text" VARCHAR DEFAULT 0,
  "resource_sap_text" VARCHAR DEFAULT 'resource_sap_text',
  "resource_science_text" VARCHAR DEFAULT 'resource_science_text',
  "resource_sunlight_max" FLOAT DEFAULT 1000,
  "resource_sap_max" FLOAT DEFAULT 200,
  "resource_treefolk_max" FLOAT DEFAULT 100,
  "resource_science_max" FLOAT DEFAULT 100,
  "resource_sap_reveal" BOOLEAN DEFAULT false,
  "resource_treefolk_reveal" BOOLEAN DEFAULT false,
  "resource_science_reveal" BOOLEAN DEFAULT false,
  "research_meterology" BOOLEAN DEFAULT false,
  "research_agriculture" BOOLEAN DEFAULT false,
  "research_irrigation" BOOLEAN DEFAULT false,
  "research_meterology_text" VARCHAR DEFAULT 'research_meterology_text',
  "research_agriculture_text" VARCHAR DEFAULT'research_agriculture_tex',
  "research_irrigation_text" VARCHAR DEFAULT 'research_irrigation_text',
  "research_meterology_cost" FLOAT DEFAULT 100,
  "research_irrigation_cost" FLOAT DEFAULT 100,
  "research_agriculture_cost" FLOAT DEFAULT 100,
  "upgrade_roots" FLOAT DEFAULT 0,
  "upgrade_chlorophyll" FLOAT DEFAULT 0,
  "upgrade_bark" FLOAT DEFAULT 0,
  "upgrade_roots_cost" FLOAT DEFAULT 2,
  "upgrade_chlorophyll_cost" FLOAT DEFAULT 2,
  "upgrade_bark_cost" FLOAT DEFAULT 100,
  "upgrade_roots_text" VARCHAR DEFAULT 100,
  "upgrade_chlorophyll_text" VARCHAR DEFAULT 'upgrade_chloro_text',
  "upgrade_bark_text" VARCHAR DEFAULT 'upgrade_bark_text',
  "upgrade_roots_reveal" BOOLEAN DEFAULT false,
  "upgrade_chlorophyll_reveal" BOOLEAN DEFAULT false,
  "upgrade_bark_reveal" BOOLEAN DEFAULT false,
  "resource_sunlight" FLOAT(30) DEFAULT 0,
  "resource_sap_cost" FLOAT DEFAULT 100,
  "resource_sunlight_reveal" BOOLEAN DEFAULT false,
  "resource_population" FLOAT DEFAULT 0,
  "resource_population_reveal" BOOLEAN DEFAULT false,
  "resource_population_max" FLOAT DEFAULT 1000,
  "resource_population_modifier" FLOAT DEFAULT 1.5,
  "resource_scientist" FLOAT DEFAULT 0,
  "resource_scientist_reveal" BOOLEAN DEFAULT false,
  "resource_scientist_max" FLOAT DEFAULT 1000,
  "resource_scientist_modifier" FLOAT DEFAULT 1.5,
  "resource_builder" FLOAT DEFAULT 0,
  "resource_builder_reveal" BOOLEAN DEFAULT false,
  "resource_builder_max" FLOAT DEFAULT 1000,
  "resource_builder_modifier" FLOAT DEFAULT 1.5,
  "resource_explorer" FLOAT DEFAULT 0,
  "resource_explorer_reveal" BOOLEAN DEFAULT false,
  "resource_explorer_max" FLOAT DEFAULT 1000,
  "resource_explorer_modifier" FLOAT DEFAULT 1.5,
  "resource_farmer" FLOAT DEFAULT 0,
  "resource_farmer_reveal" BOOLEAN DEFAULT false,
  "resource_farmer_max" FLOAT DEFAULT 1000,
  "resource_farmer_modifier" FLOAT DEFAULT 1.5,
  "resource_sunstone" FLOAT DEFAULT 0,
  "resource_sunstone_max" FLOAT DEFAULT 100,
  "resource_sunstone_text" VARCHAR DEFAULT 'a little piece of the sun',
  "resource_sunstone_modifier" FLOAT DEFAULT 1,
  "upgrade_roots_flavor_text_one" VARCHAR DEFAULT 'Your roots expand and entwine with the trees around you.',
  "upgrade_roots_flavor_text_two" VARCHAR DEFAULT 'As your roots expand, you can feel something bright below.',
  "upgrade_roots_flavor_text_three" VARCHAR DEFAULT 'As above, so below.  The warmth increases.  You are getting close.',
  "upgrade_roots_flavor_text_four" VARCHAR DEFAULT 'Your roots entwine around an object as bright as the sun in you mind.',
  "resource_sunstone_flavor_text_one" VARCHAR DEFAULT 'You have aquired a sunstone!',
  "resource_treefolk_unassigned" FLOAT DEFAULT 0,
  "resource_treefolk_assigned" FLOAT DEFAULT 0,
  "resource_sunstone_reveal" BOOLEAN DEFAULT false,
  "text_save" VARCHAR DEFAULT 'Game Saved',
  "season" FLOAT DEFAULT 2,
  "season_winter_modifer" FLOAT DEFAULT .5,
  "season_winter_text_name" VARCHAR DEFAULT  'Winter',
  "season_winter_text_flavor" VARCHAR DEFAULT  'Cool winds blow through bare branches, winter is here.',
  "season_spring_modifer" FLOAT DEFAULT  1.25,
  "season_spring_text_name" VARCHAR DEFAULT  'Spring',
  "season_spring_text_flavor" VARCHAR DEFAULT  'Leaves bud and trees sprout, spring is here.',
  "season_summer_modifer" FLOAT DEFAULT  1.5,
  "season_summer_text_name" VARCHAR DEFAULT  'Summer',
  "season_summer_text_flavor" VARCHAR DEFAULT  'Long days and warm nights, summer is here.',
  "season_fall_modifer" FLOAT DEFAULT  .75,
  "season_fall_text_name" VARCHAR DEFAULT  'Fall',
  "season_fall_text_flavor" VARCHAR DEFAULT  'Leaves turn and blow in the wind, fall is here.',
  "year" FLOAT DEFAULT  0,
  "year_text" VARCHAR DEFAULT 'A new year is here.',
  "research_horticulture" BOOLEAN DEFAULT false,
  "research_horticulture_text" VARCHAR DEFAULT 'research_horticulture_text',
  "research_horticulture_cost" FLOAT DEFAULT 100,
  "research_calendar" BOOLEAN DEFAULT false,
  "research_calendar_text" VARCHAR DEFAULT 'research_calendar_text',
  "research_calendar_cost" FLOAT DEFAULT 100,
  "resource_sunlight_modifier" FLOAT DEFAULT 1,
  "tab_production_show" BOOLEAN DEFAULT true,
  "tab_research_show" BOOLEAN DEFAULT false,
  "tab_garden_show" BOOLEAN DEFAULT false,
  "tab_population_show" BOOLEAN DEFAULT false,
  "tab_exploration_show" BOOLEAN DEFAULT false
);

