
-- USER is a reserved keyword with Postgres
-- You must use double quotes in every query that user is in:
-- ex. SELECT * FROM "user";
-- Otherwise you will have errors!
CREATE TABLE "user" (
    "id" SERIAL PRIMARY KEY, 
    "username" VARCHAR (80) UNIQUE,
    "password" VARCHAR (100),
    "isAdmin" BOOLEAN DEFAULT false,
	"click_gather_sunlight" INTEGER DEFAULT 1,
  "resource_sap" INTEGER DEFAULT 0,
  "resource_treefolk" INTEGER DEFAULT 0,
  "resource_science" INTEGER DEFAULT 0,
  "resource_sunlight_text" VARCHAR DEFAULT 0,
  "resource_sap_text" VARCHAR DEFAULT 'resource_sap_text',
  "resource_science_text" VARCHAR DEFAULT 'resource_science_text',
  "resource_sunlight_max" INTEGER DEFAULT 100,
  "resource_sap_max" INTEGER DEFAULT 100,
  "resource_treefolk_max" INTEGER DEFAULT 100,
  "resource_science_max" INTEGER DEFAULT 100,
  "resource_sap_reveal" BOOLEAN DEFAULT false,
  "resource_treefolk_reveal" BOOLEAN DEFAULT false,
  "resource_science_reveal" BOOLEAN DEFAULT false,
  "research_meterology" BOOLEAN DEFAULT false,
  "research_agriculture" BOOLEAN DEFAULT false,
  "research_irrigation" BOOLEAN DEFAULT false,
  "research_meterology_text" VARCHAR DEFAULT 'research_meterology_text',
  "research_agriculture_text" VARCHAR DEFAULT'research_agriculture_tex',
  "research_irrigation_text" VARCHAR DEFAULT 'research_irrigation_text',
  "research_meterology_cost" INTEGER DEFAULT 100,
  "research_irrigation_cost" INTEGER DEFAULT 100,
  "research_agriculture_cost" INTEGER DEFAULT 100,
  "upgrade_roots" INTEGER DEFAULT 100,
  "upgrade_chrolophyll" INTEGER DEFAULT 100,
  "upgrade_bark" INTEGER DEFAULT 100,
  "upgrade_roots_cost" INTEGER DEFAULT 100,
  "upgrade_chrolophyll_cost" INTEGER DEFAULT 100,
  "upgrade_bark_cost" INTEGER DEFAULT 100,
  "upgrade_roots_text" VARCHAR DEFAULT 100,
  "upgrade_chrolophyll_text" VARCHAR DEFAULT'upgrade_chloro_text',
  "upgrade_bark_text" VARCHAR DEFAULT 'upgrade_bark_text',
  "upgrade_roots_reveal" BOOLEAN DEFAULT false,
  "upgrade_chlorophyll_reveal" BOOLEAN DEFAULT false,
  "upgrade_bark_reveal" BOOLEAN DEFAULT false,
   "resource_sunlight" INTEGER DEFAULT 0,
  "resource_sap_price" INTEGER DEFAULT 100
);
