
-- USER is a reserved keyword with Postgres
-- You must use double quotes in every query that user is in:
-- ex. SELECT * FROM "user";
-- Otherwise you will have errors!
CREATE TABLE "user" (
    "id" SERIAL PRIMARY KEY,
    "username" VARCHAR (80) UNIQUE,
    "password" VARCHAR (100),
	"isAdmin" BOOLEAN DEFAULT false,
  "resource_sunlight" INTEGER DEFAULT 0,
  "resource_sap" INTEGER DEFAULT 0,
  "resource_treefolk" INTEGER DEFAULT 0,
  "resource_science" INTEGER DEFAULT 0,
  "resource_sunlight_text" VARCHAR DEFAULT 0,
  "resource_sap_text" VARCHAR,
  "resource_science_text" VARCHAR,
  "resource_sunlight_max" INTEGER,
  "resource_sap_max" INTEGER DEFAULT 100,
  "resource_treefolk_max" INTEGER DEFAULT 100,
  "resource_science_max" INTEGER DEFAULT 100,
  "resource_sap_reveal" BOOLEAN DEFAULT false,
  "resource_treefolk_reveal" BOOLEAN DEFAULT false,
  "resource_science_reveal" BOOLEAN DEFAULT false,
  "research_meterology" BOOLEAN DEFAULT false,
  "research_agriculture" BOOLEAN DEFAULT false,
  "research_irrigation" BOOLEAN DEFAULT false,
  "research_meterology_text" VARCHAR,
  "research_agriculture_text" VARCHAR,
  "research_irrigation_text" VARCHAR,
  "research_meterology_cost" INTEGER DEFAULT 100,
  "research_irrigation_cost" INTEGER DEFAULT 100,
  "research_agriculture_cost" INTEGER DEFAULT 100,
  "upgrade_roots" INTEGER DEFAULT 100,
  "upgrade_chrolophyll" INTEGER DEFAULT 100,
  "upgrade_bark" INTEGER DEFAULT 100,
  "upgrade_roots_cost" INTEGER DEFAULT 100,
  "upgrade_chrolophyll_cost" INTEGER DEFAULT 100,
  "upgrade_bark_cost" INTEGER DEFAULT 100,
  "upgrade_roots_text" VARCHAR DEFAULT 100,
  "upgrade_chrolophyll_text" VARCHAR,
  "upgrade_bark_text" VARCHAR,
  "upgrade_roots_reveal" BOOLEAN DEFAULT false,
  "upgrade_chlorophyll_reveal" BOOLEAN DEFAULT false,
  "upgrade_bark_reveal" BOOLEAN DEFAULT false
);