const express = require('express');
const pool = require('../modules/pool');
const router = express.Router();

/**
 * GET route template
 */
// router.get('/', (req, res) => {

// });
router.get('/', (req, res) => {
  const queryText = 'SELECT * FROM "user" WHERE "id" = $1';
  pool.query(queryText, [req.user.id])
    .then((result) => { res.send(result.rows); })
    .catch((err) => {
      console.log('Error completing SELECT everything query', err);
      res.sendStatus(500);
    });
});

router.delete('/', (req, res) => {
  const queryText = 'DELETE FROM "user" WHERE "id" = $1';
  pool.query(queryText, [req.user.id])
    .then((result) => { res.send(result.rows); })
    .catch((err) => {
      console.log('Error completing DELETE everything query', err);
      res.sendStatus(500);
    });
});

router.put('/', (req, res) => {
  const queryText =
    `UPDATE "user" 
      SET 
  "click_gather_sunlight"=$2,
  "resource_sap"=$3,
  "resource_treefolk"=$4,
  "resource_science"=$5,
  "resource_sunlight_text"=$6,
  "resource_sap_text"=$7,
  "resource_science_text"=$8,
  "resource_sunlight_max"=$9,
  "resource_sap_max"=$10,
  "resource_treefolk_max"=$11,
  "resource_science_max"=$12,
  "resource_sap_reveal"=$13,
  "resource_treefolk_reveal"=$14,
  "resource_science_reveal"=$15,
  "research_meterology"=$16,
  "research_agriculture"=$17,
  "research_irrigation"=$18,
  "research_meterology_text"=$19,
  "research_agriculture_text"=$20,
  "research_irrigation_text"=$21,
  "research_meterology_cost"=$22,
  "research_irrigation_cost"=$23,
  "research_agriculture_cost"=$24,
  "upgrade_roots"=$25,
  "upgrade_chlorophyll"=$26,
  "upgrade_bark"=$27,
  "upgrade_roots_cost"=$28,
  "upgrade_chlorophyll_cost"=$29,
  "upgrade_bark_cost"=$30,
  "upgrade_roots_text" =$31,
  "upgrade_chlorophyll_text" =$32,
  "upgrade_bark_text" =$33,
  "upgrade_roots_reveal"=$34,
  "upgrade_chlorophyll_reveal"=$35,
  "upgrade_bark_reveal" =$36,
  "resource_sunlight"=$37,
  "resource_sap_cost"=$38,
  "resource_sunlight_reveal"=$39,
  "resource_population" =$40,
  "resource_population_reveal" =$41,
  "resource_population_max" =$42,
  "resource_population_modifier" =$43,
  "resource_scientist" =$44,
  "resource_scientist_reveal" =$45,
  "resource_scientist_max" =$46,
  "resource_scientist_modifier" =$47,
  "resource_builder" =$48,
  "resource_builder_reveal" =$49,
  "resource_builder_max" =$50,
  "resource_builder_modifier" =$51,
  "resource_explorer" =$52,
  "resource_explorer_reveal" =$53,
  "resource_explorer_max" =$54,
  "resource_explorer_modifier" =$55,
  "resource_farmer" =$56,
  "resource_farmer_reveal" =$57,
  "resource_farmer_max" =$58,
  "resource_farmer_modifier" =$59,
  "resource_sunstone" =$60,
  "resource_sunstone_max" =$61,
  "resource_sunstone_text" =$62,
  "resource_sunstone_modifier" =$63,
  "upgrade_roots_flavor_text_one" =$64,
  "upgrade_roots_flavor_text_two" =$65,
  "upgrade_roots_flavor_text_three" =$66,
  "upgrade_roots_flavor_text_four" =$67,
  "resource_sunstone_flavor_text_one"=$68,
  "resource_treefolk_unassigned"=$69,
  "resource_treefolk_assigned"=$70,
  "resource_sunstone_reveal"=$71,
  "text_save"=$72,
  "season"=$73,
  "season_winter_modifer"=$74,
  "season_winter_text_name"=$75,
  "season_winter_text_flavor"=$76,
  "season_spring_modifer"=$77,
  "season_spring_text_name" =$78,
  "season_spring_text_flavor" =$79,
  "season_summer_modifer" =$80,
  "season_summer_text_name" =$81,
  "season_summer_text_flavor" =$82,
  "season_fall_modifer" =$83,
  "season_fall_text_name" =$84,
  "season_fall_text_flavor" =$85,
  "year" =$86,
  "year_text" =$87,
  "research_horticulture" =$88,
  "research_horticulture_text"=$89,
  "research_horticulture_cost" =$90,
  "research_calendar" =$91,
  "research_calendar_text" =$92,
  "research_calendar_cost"=$93,
  "resource_sunlight_modifier"=$94,
  "tab_production_show"=$95,
  "tab_research_show"=$96,
  "tab_garden_show"=$97,
  "tab_population_show"=$98,
  "tab_exploration_show"=$99,
  "garden_bush"=$100,
  "garden_bush_cost"=$101,
  "garden_bush_text_one"=$102,
  "garden_bush_text_two"=$103,
  "garden_bush_text_three"=$104, 
  "garden_bush_text_four"=$105, 
  "garden_bush_reveal"=$106,
  "garden_fern"=$107,
  "garden_fern_cost"=$108, 
  "garden_fern_text_one"=$109, 
  "garden_fern_text_two"=$110,
  "garden_fern_text_three"=$111,
  "garden_fern_text_four"=$112, 
  "garden_fern_reveal"=$113,
  "garden_flower"=$114,
  "garden_flower_cost"=$115, 
  "garden_flower_text_one"=$116,
  "garden_flower_text_two"=$117,
  "garden_flower_text_three"=$118,
  "garden_flower_text_four"=$119,
  "garden_flower_reveal"=$120,
  "resource_gardener"=$121,
  "resource_gardener_reveal"=$122,
  "resource_gardener_max"=$123,
  "resource_gardener_modifier"=$124,
  "resource_soil"=$125,
  "resource_soil_reveal"=$126,
  "resource_soil_max"=$127,
  "resource_soil_text"=$128,
  "exploration_forest"=$129,
  "exploration_forest_max"=$130,
  "exploration_reveal"=$131,
  "research_mathematics"=$132,
  "research_mobility"=$133,
  "research_sunstone"=$134,
  "research_mathematics_text"=$135,
  "research_mobility_text"=$136,
  "research_sunstone_text"=$137,
  "research_mathematics_cost"=$138,
  "research_mobility_cost"=$139,
  "research_sunstone_cost"=$140
    WHERE "id"=$1`;
  const values = [
    req.user.id,
    req.body.click_gather_sunlight,
    req.body.resource_sap,
    req.body.resource_treefolk,
    req.body.resource_science,
    req.body.resource_sunlight_text,
    req.body.resource_sap_text,
    req.body.resource_science_text,
    req.body.resource_sunlight_max,
    req.body.resource_sap_max,
    req.body.resource_treefolk_max,
    req.body.resource_science_max,
    req.body.resource_sap_reveal,
    req.body.resource_treefolk_reveal,
    req.body.resource_science_reveal,
    req.body.research_meterology,
    req.body.research_agriculture,
    req.body.research_irrigation,
    req.body.research_meterology_text,
    req.body.research_agriculture_text,
    req.body.research_irrigation_text,
    req.body.research_meterology_cost,
    req.body.research_irrigation_cost,
    req.body.research_agriculture_cost,
    req.body.upgrade_roots,
    req.body.upgrade_chlorophyll,
    req.body.upgrade_bark,
    req.body.upgrade_roots_cost,
    req.body.upgrade_chlorophyll_cost,
    req.body.upgrade_bark_cost,
    req.body.upgrade_roots_text,
    req.body.upgrade_chlorophyll_text,
    req.body.upgrade_bark_text,
    req.body.upgrade_roots_reveal,
    req.body.upgrade_chlorophyll_reveal,
    req.body.upgrade_bark_reveal,
    req.body.resource_sunlight,
    req.body.resource_sap_cost,
    req.body.resource_sunlight_reveal,
    req.body.resource_population,
    req.body.resource_population_reveal,
    req.body.resource_population_max,
    req.body.resource_population_modifier,
    req.body.resource_scientist,
    req.body.resource_scientist_reveal,
    req.body.resource_scientist_max,
    req.body.resource_scientist_modifier,
    req.body.resource_builder,
    req.body.resource_builder_reveal,
    req.body.resource_builder_max,
    req.body.resource_builder_modifier,
    req.body.resource_explorer,
    req.body.resource_explorer_reveal,
    req.body.resource_explorer_max,
    req.body.resource_explorer_modifier,
    req.body.resource_farmer,
    req.body.resource_farmer_reveal,
    req.body.resource_farmer_max,
    req.body.resource_farmer_modifier,
    req.body.resource_sunstone,
    req.body.resource_sunstone_max,
    req.body.resource_sunstone_text,
    req.body.resource_sunstone_modifier,
    req.body.upgrade_roots_flavor_text_one,
    req.body.upgrade_roots_flavor_text_two,
    req.body.upgrade_roots_flavor_text_three,
    req.body.upgrade_roots_flavor_text_four,
    req.body.resource_sunstone_flavor_text_one,
    req.body.resource_treefolk_unassigned,
    req.body.resource_treefolk_assigned,
    req.body.resource_sunstone_reveal,
    req.body.text_save,
    req.body.season,
    req.body.season_winter_modifer,
    req.body.season_winter_text_name,
    req.body.season_winter_text_flavor,
    req.body.season_spring_modifer,
    req.body.season_spring_text_name,
    req.body.season_spring_text_flavor,
    req.body.season_summer_modifer,
    req.body.season_summer_text_name,
    req.body.season_summer_text_flavor,
    req.body.season_fall_modifer,
    req.body.season_fall_text_name,
    req.body.season_fall_text_flavor,
    req.body.year,
    req.body.year_text,
    req.body.research_horticulture,
    req.body.research_horticulture_text,
    req.body.research_horticulture_cost,
    req.body.research_calendar,
    req.body.research_calendar_text,
    req.body.research_calendar_cost,
    req.body.resource_sunlight_modifier,
    req.body.tab_production_show,
    req.body.tab_research_show,
    req.body.tab_garden_show,
    req.body.tab_population_show,
    req.body.tab_exploration_show,
    req.body.garden_bush,
    req.body.garden_bush_cost,
    req.body.garden_bush_text_one, 
    req.body.garden_bush_text_two,
    req.body.garden_bush_text_three, 
    req.body.garden_bush_text_four,
    req.body.garden_bush_reveal, 
    req.body.garden_fern,
    req.body.garden_fern_cost,
    req.body.garden_fern_text_one, 
    req.body.garden_fern_text_two,
    req.body.garden_fern_text_three, 
    req.body.garden_fern_text_four,
    req.body.garden_fern_reveal,
    req.body.garden_flower,
    req.body.garden_flower_cost,
    req.body.garden_flower_text_one,
    req.body.garden_flower_text_two,
    req.body.garden_flower_text_three,
    req.body.garden_flower_text_four, 
    req.body.garden_flower_reveal,
    req.body.resource_gardener,
    req.body.resource_gardener_reveal,
    req.body.resource_gardener_max,
    req.body.resource_gardener_modifier,
    req.body.resource_soil,
    req.body.resource_soil_reveal,
    req.body.resource_soil_max,
    req.body.resource_soil_text,
    req.body.exploration_forest,
    req.body.exploration_forest_max,
    req.body.exploration_reveal,
    req.body.esearch_mathematics,
    req.body.research_mobility,
    req.body.research_sunstone,
    req.body.research_mathematics_text,
    req.body.research_mobility_text,
    req.body.research_sunstone_text,
    req.body.research_mathematics_cost,
    req.body.research_mobility_cost,
    req.body.research_sunstone_cost,
  ];

  pool.query(queryText, values)
    .then((result) => { res.send(result.rows); })
    .catch((err) => {
      console.log('Error completing put route query', err);
      res.sendStatus(500);
    });
});

/**
 * POST route template
 */
router.post('/', (req, res) => {

});

module.exports = router;